### ISSUE TITLE
Same error with latest version

### ISSUE THREAD

**Issue by AviatorBimmer** [vectronic/homebridge-jvc-projector#11]
Hey guys, Homebridge installed via Docker on Synology NAS here and I still get this error when I install the latest version of the plugin.

`[1/30/2023, 6:34:45 AM] [JV NX7 projector] stateTimeout error: Error: Command failed: /usr/bin/python /homebridge/node_modules/homebridge-jvc-projector/dist/get_power_state.py 192.168.183.6 
Traceback (most recent call last):
  File "/homebridge/node_modules/homebridge-jvc-projector/dist/get_power_state.py", line 3, in <module>
    from jvc_projector_remote import JVCProjector
ImportError: No module named jvc_projector_remote`

**Comment by vectronic** [comment]
Not sure what to say here, all the reports I got from others is that the current version is the correct way it should be...

**Comment by vectronic** [comment]
Just going through tickets - not sure if this is still an issue or you have moved on...

Maybe check you have the latest python module version that this plugin relies on:

I think you can do this with:

`python3 -m pip install jvc-projector-remote --upgrade`

**Comment by AviatorBimmer** [comment]
> Just going through tickets - not sure if this is still an issue or you have moved on...
> 
> Maybe check you have the latest python module version that this plugin relies on:
> 
> I think you can do this with:
> 
> `python3 -m pip install jvc-projector-remote --upgrade`

I gave up on this. Never got it working. Thanks anyway.
