### ISSUE TITLE
Permission denied

### ISSUE THREAD

**Issue by MarinoKNX** [vectronic/homebridge-jvc-projector#12]
Hi,
I installed v1.3.1 of your plugin to control my JVC NZ7.

Homebridge is in a docker and the JVC Projector Remote package is installed.

In Status now I get this:
`[4/10/2023, 9:26:41 AM] [JVC NZ7] stateTimeout error: Error: Command failed: /usr/local/lib/python3.8 /homebridge/node_modules/homebridge-jvc-projector/dist/get_power_state.py (Here is my IP)
/bin/sh: 1: /usr/local/lib/python3.8: Permission denied`

I read something what I could do about that but I was more confused in the end if I should do this (changing permission from root to homebridge).

What should I do when I have this permission problem?

Kind regards
Nils

**Comment by vectronic** [comment]
I think you might have the wrong config for `python_path`. This should be the executable for python, not the location of the installation. `/usr/local/lib/python3.8` looks like a directory of installation to me.

You _might_ have luck identifying the executable path by running:

`which python3`

At a guess, based on that library folder path, `/usr/local/bin/python3` might work.

**Comment by MarinoKNX** [comment]
Hi,
which python3 gives me "/usr/bin/python3". With this path it seems to be working. I'll need maybe a few days to test this out, but I'll give you a feedback.

Thanks 
Nils

**Comment by MarinoKNX** [comment]
I was able to test this earlier than expected. Now it works perfect (NZ7).

Thank you very much for your help and of cause for the plugin ;)

**Comment by vectronic** [comment]
Good to hear!
