### ISSUE TITLE
How to install jvc_projector_remote project manually?

### ISSUE THREAD

**Issue by AviatorBimmer** [vectronic/homebridge-jvc-projector#3]
How can I install the jvc_projector_remote manually via Hoobs terminal? I can't figure out the syntax. Thanks in advance!

**Comment by vectronic** [comment]
I use homebridge only, not Hoobs. 

In the readme file I provide instructions for manually installing for homebridge. I don’t know how this applies to hoobs. 

You might be better asking on a hoobs forum.

**Comment by AviatorBimmer** [comment]
Oh wow, I didn't realize it was the Homebridge forum and not the Hoobs forum. Sorry about that.

Thanks,

Efrain R.

***** This email was composed and sent from my mobile device. Excuse my grammar and pardon my brevity. *****
