### ISSUE TITLE
Synology NAS homebridge does not work

### ISSUE THREAD

**Issue by clayton718** [vectronic/homebridge-jvc-projector#7]
I'm using synology NAS as homebridge hub, however, after install this plugin, it shows the following error message in the logs:

stateTimeout error: Error: Command failed: /usr/bin/python /volume1/homebridge/node_modules/homebridge-jvc-projector/dist/get_power_state.py 192.1681.211 
Traceback (most recent call last):
  File "/volume1/homebridge/node_modules/homebridge-jvc-projector/dist/get_power_state.py", line 1, in <module>
    from jvc_projector import JVCProjector
ModuleNotFoundError: No module named 'jvc_projector'

In the homepage of my synology's homebridge it shows my path is the follwings, but not python path.
Storage Path :  /volume1/homebridge/
Config Path:  /volume1/homebridge/config.json
Plugin Path: /volume1/homebridge/node_modules

please help.

**Comment by vectronic** [comment]
From the readme:

Install the python project: pip install -e git+https://github.com/bezmi/jvc_projector.git#egg=jvc-projector-remote

**Comment by clayton718** [comment]
Thank you so much for replying to my email. I read the readme already and
tried to install this python project, however I'm stupid in programming.
I've tried to install this in the terminal of the homebridge system. but it
shows pip command not found. It would be appreciated if you can tell me how
to install that python project in my homebridge.

Best regards,
Clayton

[image: 螢幕截圖 2022-11-22 下午11.22.16.png]

**Comment by vectronic** [comment]
Do a google search for: "how to install python and pip on synology nas"

**Comment by clayton718** [comment]
I spend ten hours to try, but is was too complicated. 
I enabled SSH service in synology DSM and used terminal in my Imac to login in the sysnology.
I've successfully in stall python 3.9, it was easy becuase the synology package center can install it directly.
Next, I tried many ways to install pip. Only this succss for me
in the terminal type "sudo python3 -m ensurepip" then the following appears:

Looking in links: /tmp/tmpyii1sl41
Requirement already satisfied: setuptools in /usr/lib/python3.8/site-packages (56.0.0)
Requirement already satisfied: pip in /usr/lib/python3.8/site-packages (22.3.1) 

Not matter what path input in the setting of plugin, it shows only like this:
stateTimeout error: Error: Command failed: /usr/bin/python3 /volume1/homebridge/node_modules/homebridge-jvc-projector/dist/get_power_state.py 192.1681.211 
Traceback (most recent call last):
  File "/volume1/homebridge/node_modules/homebridge-jvc-projector/dist/get_power_state.py", line 1, in <module>
    from jvc_projector import JVCProjector
ModuleNotFoundError: No module named 'jvc_projector'

or like this

stateTimeout error: Error: Command failed: /volume1/@appstore/Python3.9 /volume1/homebridge/node_modules/homebridge-jvc-projector/dist/get_power_state.py 192.1681.211 
/bin/sh: /volume1/@appstore/Python3.9: Is a directory

**Comment by piejanssens** [comment]
Try this command via SSH: `/bin/python3 -m pip install jvc-projector-remote`
