### ISSUE TITLE
Specify version from pypi for jvc_projector module 

### ISSUE THREAD

**Issue by bezmi** [vectronic/homebridge-jvc-projector#9]
Hi, I notice that your README specifies `pip install -e git+https://github.com/bezmi/jvc_projector.git#egg=jvc-projector-remote` for the package. Please change this to a [release version from pypi](https://pypi.org/project/jvc-projector-remote/). Development is done directly on the main branch, so stability issues may arise.

The current version is incompatible with python <=3.8 (fix coming):
[oznu/docker-homebridge#491](https://github.com/oznu/docker-homebridge/issues/491)
[bezmi/jvc_projector#19](https://github.com/bezmi/jvc_projector/issues/19)

Staying pinned to a working version and doing testing before bumping it would be preferable.

**Comment by vectronic** [comment]
This was done in v1.3.1 - thanks for your input.

**Comment by bezmi** [comment]
note, v0.2.3 has been released on pypi which fixes the python 3.8 compatibility issues.
